name: Reusable - Sync main back to beta after release

on:
  workflow_call:
    inputs:
      main_branch:
        type: string
        required: false
        default: "main"
      beta_branch:
        type: string
        required: false
        default: "beta"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.main_branch }}
          fetch-depth: 0

      - name: Force push main to beta
        run: git push origin ${{ inputs.main_branch }}:${{ inputs.beta_branch }} --force
